### ISSUE TITLE
pip install -r requirements-dev.txt produces an error

### ISSUE THREAD

**Issue by vmelnych** [RasaHQ/helpdesk-assistant#33]
When executing the command, 'pip install -r requirements-dev.txt' I get the error below. My environment Ubuntu 20.04, python 3.7.

Building wheels for collected packages: pytype, importlab
  Building wheel for pytype (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c1j6y1u8/pytype/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c1j6y1u8/pytype/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yk48x1gy
       cwd: /tmp/pip-install-c1j6y1u8/pytype/
  Complete output (1434 lines):
  /usr/lib/python3/dist-packages/setuptools/dist.py:476: UserWarning: Normalizing '2019.07.11' to '2019.7.11'
    normalized_version,

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by vmelnych** [comment]
Figured out it works with Python 3.6-dev only (and pip3). The guaranteed working environment needs to be documented exactly.
